[package]
name = "linear_regression"
version = "0.1.0"
description = "A first attempt at linear regression with Cairo 1.0"
homepage = "https://github.com/teddyjfpender/cairo-linear-regression"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."
# Add your own custom commands and run them with scarb run <command>

[dependencies]
onnx_cairo = { git = "https://github.com/franalgaba/onnx-cairo" }